### ISSUE TITLE
Proprietary extraction fails

### ISSUE THREAD

**Issue by waltercool** [whatawurst/android_device_samsung_beyond1lte#10]
Hi there,

Tried to compile this from my side using images from last version (G973FXXU4CTC9) , and extract proprietary script fails at two points:

File doesn't exist (system/lib64 from system.img): https://github.com/whatawurst/android_device_samsung_beyond1lte/blob/ac2d8a534eb81883def3cc92b74664dd90d8ae9c/proprietary-files.txt#L4
File exists, but script can't find it, always fails even if path is correct (root from system.img): https://github.com/whatawurst/android_device_samsung_beyond1lte/blob/ac2d8a534eb81883def3cc92b74664dd90d8ae9c/proprietary-files.txt#L86

Had to comment them.
Q: Is extract files needed, or should we just use the provided? As understanding some blobs exists even without Samsung included them?

Thanks

**Comment by Linux4** [comment]
Hi, 

for libaptXHD_encoder.so just use https://github.com/whatawurst/android_vendor_samsung_beyond1lte as base for vendor/samsung/beyond1lte, as it's a pinned vendor file (see the hash at the end of that line) which is included in that repo.
For that init.rilmptcp.rc, can you tell me how exactly you tried to extract the blobs?

Yes of course you need to extract the proprietary files, the beyond1lte vendor repo just contains some pinned blobs but not all the blobs you need.

**Comment by waltercool** [comment]
No problem!

For rilmptcp.rc, I see this message

```
Extracting 123 files in ./proprietary-files.txt from /media/:
  - init.rilmptcp.rc
    !! init.rilmptcp.rc: file not found in source
```

Strangly, the file exists at my /media/ root path, as I got system.img mounted at that place. No problems for other files, just that one.
```

# ls /media/init.rilmptcp.rc  -la
-rwxr-x--- 1 root 2000 454 Dec 31  2008 /media/init.rilmptcp.rc
```

**Comment by waltercool** [comment]
I do apologize for all, seems like system.img has no public access to the file. I'm building with a restricted user, so can't fetch the file.

Thanks for your suggestions! Will use the blob from repo for APT HD codec.
